---
title: "week6_homework"
output: html_document
date: "2024-11-18"
---

```{r}
#first library a few packages that we will use during the practical
#note you may need to install them first...

library(spatstat) #spatial point processes
library(here)
library(sp)
library(tmap)
library(sf)
library(tmaptools)
library(stringr)
library(tidyverse)
library(fpc) #DBSCAN
```

```{r}
#load data
londonboundary <- st_read(here::here("/Users/tsernian/Documents/CASA/CASA0005_GIS and Science/CASA0005_GIS-and-Science/week6/data/ESRI/London_Borough_Excluding_MHW.shp")) %>%
  st_transform(., 27700)

BluePlaques <- st_read("https://s3.eu-west-2.amazonaws.com/openplaques/open-plaques-london-2018-04-08.geojson") %>%
  st_transform(., 27700)
print(BluePlaques)
```

```{r}
boroughmap <- londonboundary %>%
  dplyr::filter(str_detect(GSS_CODE, "^E09"))%>%
  st_transform(., 27700)

qtm(boroughmap)
```

```{r}
#plot the blue plaques in the city
tmap_mode("plot")
tm_shape(boroughmap) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(BluePlaques) +
  tm_dots(col = "green")
```

```{r}
#remove duplicates
BluePlaques <- distinct(BluePlaques) #distinct is the function to remove the points which are out site the Boroughs

BluePlaquesSub <- BluePlaques[boroughmap,]
#check to see that they've been removed
tmap_mode("plot")
tm_shape(boroughmap) +
  tm_polygons(col = NA, alpha = 0.5) +
tm_shape(BluePlaquesSub) +
  tm_dots(col = "green")
```

```{r}
#extract the borough

# select by attribute
Harrow <- boroughmap %>%
  filter(., NAME =="Harrow")

#Check to see that the correct borough has been pulled out
tm_shape(Harrow) +
  tm_polygons(col = NA, alpha = 0.5)
```

```{r}
BluePlaquesSub <- BluePlaques[Harrow,]
#check that it's worked
tmap_mode("plot")

tm_shape(Harrow) +
  tm_polygons(col = NA, alpha = 0.2) +
tm_shape(BluePlaquesSub) +
  tm_dots(col = "green", size = 0.5)
```

```{r}
#now set a window as the borough boundary
window <- as.owin(Harrow)
plot(window)
```

```{r}
#create a sp object
BluePlaquesSub<- BluePlaquesSub %>%
  as(., 'Spatial')
#create a ppp object
BluePlaquesSub.ppp <- ppp(x=BluePlaquesSub@coords[,1],
                          y=BluePlaquesSub@coords[,2],
                          window=window)
```

```{r}
BluePlaquesSub.ppp %>%
  plot(.,pch=16,cex=0.5, 
       main="Blue Plaques Harrow")
```

```{r}
#Kernel Density Estimation
BluePlaquesSub.ppp %>%
  density(., sigma=500) %>%
  plot()
```

```{r}
BluePlaquesSub.ppp %>%
  density(., sigma=1000) %>%
  plot()
```

```{r}
#Quadrat Analysis
#First plot the points
plot(BluePlaquesSub.ppp,
     pch=16,
     cex=0.5, 
     main="Blue Plaques in Harrow")

#now count the points in that fall in a 6 x 6
#grid overlaid across the windowBluePlaquesSub.ppp2<-BluePlaquesSub.ppp %>%
BluePlaquesSub.ppp %>%
  quadratcount(.,nx = 6, ny = 6)%>%
    plot(., add=T, col="red")
```

```{r}
#run the quadrat count
Qcount <- BluePlaquesSub.ppp %>%
  quadratcount(.,nx = 6, ny = 6) %>%
  as.data.frame() %>%
  dplyr::count(Var1=Freq)%>%
  dplyr::rename(Freqquadratcount=n)

Qcount %>% 
  summarise_all(class)
```

```{r}
sums <- Qcount %>%
  #calculate the total blue plaques (Var * Freq)
  mutate(total = Var1 * Freqquadratcount) %>%
  dplyr::summarise(across(everything(), sum))%>%
  dplyr::select(-Var1) 

lambda<- Qcount%>%
  #calculate lambda
  mutate(total = Var1 * Freqquadratcount)%>%
  dplyr::summarise(across(everything(), sum)) %>%
  mutate(lambda=total/Freqquadratcount) %>%
  dplyr::select(lambda)%>%
  pull(lambda)
```

```{r}
QCountTable <- Qcount %>%
  mutate(Pr=((lambda^Var1)*exp(-lambda))/factorial(Var1))%>%
  #now calculate the expected counts based on our total number of plaques
  #and save them to the table
  mutate(Expected= (round(Pr * sums$Freqquadratcount, 0)))

#Compare the frequency distributions of the observed and expected point patterns
plot(c(1,5),c(0,14), type="n",
xlab="Number of Blue Plaques (Red=Observed,Blue=Expected)", 
     ylab="Frequency of Occurances")
points(QCountTable$Freqquadratcount, 
       col="Red", 
       type="o", 
       lwd=3)
points(QCountTable$Expected, col="Blue", 
       type="o", 
       lwd=3)
```

```{r}
teststats <- quadrat.test(BluePlaquesSub.ppp, nx = 6, ny = 6)

plot(BluePlaquesSub.ppp,pch=16,cex=0.5, main="Blue Plaques in Harrow")
plot(teststats, add=T, col = "red")
```

```{r}
K <- BluePlaquesSub.ppp %>%
  Kest(., correction="border") %>%
  plot()
```

```{r}
st_geometry(boroughmap)

#BluePlaquesSub <- BluePlaques[Harrow,]
BluePlaquesSubPoints <- BluePlaquesSub %>%
  st_coordinates() %>% 
  as.data.frame()

db <- BluePlaquesSubPoints %>%
  fpc::dbscan(., eps =700, MinPts = 4)

plot(db, BluePlaquesSubPoints, main = "DBSCAN Output", frame = FALSE)
plot(st_geometry(boroughmap), add = TRUE)
```

```{r}
# used to find suitable eps value based on the knee in plot
# k is no of nearest neighbours used, use min points
library(dbscan)

for (k in c(4)) {
  cat("\nPlotting for k =", k, "\n")
  kNNdistplot(BluePlaquesSubPoints, k = k)
  title(main = paste("kNN Distance Plot (k =", k, ")"))
}
```

```{r}
library(ggplot2)
db
db$cluster
```

```{r}
BluePlaquesSubPoints<- BluePlaquesSubPoints %>%
  mutate(dbcluster=db$cluster)
print(BluePlaquesSubPoints)
```

```{r}
chulls <- BluePlaquesSubPoints %>%
  group_by(dbcluster) %>%
  dplyr::mutate(hull = 1:n(),
  hull = factor(hull, chull(X, Y)))%>%
  arrange(hull)

chulls <- chulls %>%
  filter(dbcluster >=1)
```

```{r}
dbplot <- ggplot(data=BluePlaquesSubPoints, 
                 aes(X,Y, colour=dbcluster, fill=dbcluster)) 
#add the points in
dbplot <- dbplot + geom_point()
#now the convex hulls
dbplot <- dbplot + geom_polygon(data = chulls, 
                                aes(X,Y, group=dbcluster), 
                                alpha = 0.5) 

#now plot, setting the coordinates to scale correctly and as a black and white plot 
#(just for the hell of it)...
dbplot + theme_bw() + coord_equal()
```

```{r}
# 1. Convert BluePlaquesSubPoints to an sf object and transform to WGS84
BluePlaquesSubPoints_sf <- st_as_sf(BluePlaquesSubPoints, 
                                    coords = c("X", "Y"), 
                                    crs = 27700)  # UK National Grid system
BluePlaquesSubPoints_sf <- st_transform(BluePlaquesSubPoints_sf, crs = 4326)  # Transform to WGS84

# 2. Compute convex hulls for each cluster
chulls <- BluePlaquesSubPoints_sf %>%
  filter(dbcluster != 0) %>%  # Exclude noise points
  group_by(dbcluster) %>%
  summarise(geometry = st_union(st_convex_hull(st_combine(geometry)))) %>%
  ungroup()  # Ungroup to allow further processing
chulls_sf <- st_as_sf(chulls)  # Ensure the output is an sf object

# 3. Create a static map
static_map <- tm_shape(BluePlaquesSubPoints_sf) +
  tm_bubbles(size = 0.5, col = "dbcluster", palette = "Set1", alpha = 0.8) +
  tm_shape(chulls_sf) +
  tm_fill(col = "dbcluster", alpha = 0.3, palette = "Set1") +
  tm_layout(legend.outside = TRUE) +
  tm_basemap(server = "OpenStreetMap")

# Display the static map
print(static_map)

# 4. Create an interactive map
tmap_mode("view")  # Enable interactive mode
interactive_map <- tm_shape(BluePlaquesSubPoints_sf) +
  tm_bubbles(size = 0.5, col = "dbcluster", palette = "Set1", alpha = 0.8) +
  tm_shape(chulls_sf) +
  tm_fill(col = "dbcluster", alpha = 0.3, palette = "Set1")

# Display the interactive map
interactive_map

```

