---
title: "week5_homework"
output: html_document
date: "2024-11-06"
---
```{r}
#library
library(sf)
library(tidyverse)
library(tmap)
library(tmaptools)
library(here)
library(grid)
library(leafpop)
library(leaflet)
```

```{r}
#load data
londonboundry <- st_read(here::here("/Users/tsernian/Documents/CASA/CASA0005_GIS and Science/CASA0005_GIS and Science/week5/data/statistical-gis-boundaries-london/ESRI/London_Borough_Excluding_MHW.shp")) %>%
  st_transform(., 27700)

osm <- st_read(here::here("/Users/tsernian/Documents/CASA/CASA0005_GIS and Science/CASA0005_GIS and Science/week5/data/greater-london-latest-free.shp/gis_osm_pois_a_free_1.shp")) %>%
  st_transform(., 27700) %>%
  dplyr::filter(fclass == 'hotel')

worldcities <- st_read(here::here("/Users/tsernian/Documents/CASA/CASA0005_GIS and Science/CASA0005_GIS and Science/week5/data/World_Cities.shp/World_Cities.shp")) %>%
  st_transform(., 27700)

ukoutline <- st_read(here::here("/Users/tsernian/Documents/CASA/CASA0005_GIS and Science/CASA0005_GIS and Science/week5/data/gadm41_GBR_shp/gadm41_GBR_0.shp")) %>%
  st_transform(., 27700)


airbnb <- read_csv("/Users/tsernian/Documents/CASA/CASA0005_GIS and Science/CASA0005_GIS and Science/week5/data/listings.csv") %>%
  st_as_sf(., coords = c("longitude", "latitude"), 
                   crs = 4326) %>%
    st_transform(., 27700)%>%
    #select entire places that are available all year
    filter(room_type == 'Entire home/apt' & availability_365 =='365')
head(airbnb)
```

```{r}
#spatial data join function
Joinfun1 <- function(data1, data2){
  output<- data1%>%
  st_join(data2,.) %>%
  add_count(GSS_CODE, name="hotels_in_borough") 

  return(output)
}

hotels <- Joinfun1(osm, londonboundry)
airbnb2 <- Joinfun1(airbnb, londonboundry)
head(hotels)
head(airbnb2)
```               

```{r}
#count how many hotels and airbnb in the london polygon
hotels <- hotels %>%
  group_by(., GSS_CODE, NAME)%>%
  summarise(`Accomodation count` = unique(hotels_in_borough))
head(hotels)

airbnb2 <- airbnb2 %>%
  group_by(., GSS_CODE, NAME)%>%
  summarise(`Accomodation count` = unique(hotels_in_borough))
head(airbnb2)
```

```{r}
tmap_mode("plot")

# set the breaks
# for our mapped data
breaks = c(0, 5, 12, 26, 57, 286) 

# plot each map
tm1 <- tm_shape(hotels) + 
  tm_polygons("Accomodation count", 
              breaks=breaks,
              palette="PuBu")+
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(a)", position=c(0,0.85), size=1.5)

tm2 <- tm_shape(airbnb2) + 
  tm_polygons("Accomodation count",
              breaks=breaks, 
              palette="PuBu") + 
  tm_legend(show=FALSE)+
  tm_layout(frame=FALSE)+
  tm_credits("(b)", position=c(0,0.85), size=1.5)

legend <- tm_shape(hotels) +
    tm_polygons("Accomodation count",
                breaks=breaks,
                palette="PuBu") +
    tm_scale_bar(position=c(0.2,0.04), text.size=0.6)+
    tm_compass(north=0, position=c(0.65,0.6))+
    tm_layout(legend.only = TRUE, legend.position=c(0.2,0.25),asp=0.1)+
    tm_credits("(c) OpenStreetMap contrbutors and Air b n b", position=c(0.0,0.0))
```

```{r}
worldcities2 <- worldcities %>%
  filter(CNTRY_NAME=='United Kingdom'&
           worldcities$CITY_NAME=='Birmingham'|
           worldcities$CITY_NAME=='London'|
           worldcities$CITY_NAME=='Edinburgh')

newbb <- c(xmin=-296000, ymin=5408, xmax=655696, ymax=1000000)
  
ukoutlinecrop <- ukoutline$geometry %>%
  st_crop(., newbb)

tm3 <- tm_shape(ukoutlinecrop)+ 
  tm_polygons(col="darkslategray1")+
  tm_layout(frame=FALSE)+
  tm_shape(worldcities2) +
  tm_symbols(col = "red", scale = .5)+
  tm_text("CITY_NAME", xmod=-1, ymod=-0.5)
```

```{r}
#library(grid)
# erases the current device or moves to a new page 
# probably not needed but makes sure you are plotting on a new page.
grid.newpage()

pushViewport(viewport(layout=grid.layout(2,2)))
print(tm1, vp=viewport(layout.pos.col=1, layout.pos.row=1, height=5))
print(tm2, vp=viewport(layout.pos.col=2, layout.pos.row=1, height=5))
print(tm3, vp=viewport(layout.pos.col=1, layout.pos.row=2, height=5))
print(legend, vp=viewport(layout.pos.col=2, layout.pos.row=2, height=5))
```

```{r}
tmap_mode("view")

tm_shape(airbnb2) + 
  tm_polygons("Accomodation count", breaks=breaks) 
```

```{r}
# library for pop up boxes
#library(leafpop)
#library(leaflet)

#join data
Joined <- airbnb2%>%
  st_join(., hotels, join = st_equals)%>%
  dplyr::select(GSS_CODE.x, NAME.x, `Accomodation count.x`, `Accomodation count.y`)%>%
  dplyr::rename(`GSS code` =`GSS_CODE.x`,
                `Borough` = `NAME.x`,
                `Airbnb count` = `Accomodation count.x`,
                `Hotel count`= `Accomodation count.y`)%>%
  st_transform(., 4326)
  
  
#remove the geometry for our pop up boxes to avoid
popupairbnb <-Joined %>%
  st_drop_geometry()%>%
  dplyr::select(`Airbnb count`, Borough)%>%
  popupTable()

popuphotel <-Joined %>%
  st_drop_geometry()%>%
  dplyr::select(`Hotel count`, Borough)%>%
  popupTable()

tmap_mode("view")

# set the colour palettes using our previously defined breaks


pal1 <- Joined %>%
  colorBin(palette = "YlOrRd", domain=.$`Airbnb count`, bins=breaks)

pal1 <-colorBin(palette = "YlOrRd", domain=Joined$`Airbnb count`, bins=breaks)

pal2 <- Joined %>%
  colorBin(palette = "YlOrRd", domain=.$`Hotel count`, bins=breaks)


map<- leaflet(Joined) %>%

  #add our polygons, linking to the tables we just made
  addPolygons(color="white", 
              weight = 2,
              opacity = 1,
              dashArray = "3",
              popup = popupairbnb,
              fillOpacity = 0.7,
              fillColor = ~pal2(`Airbnb count`),
              group = "Airbnb")%>%
  
  addPolygons(fillColor = ~pal2(`Hotel count`), 
              weight = 2,
              opacity = 1,
              color = "white",
              dashArray = "3",
              popup = popupairbnb,
              fillOpacity = 0.7,group = "Hotels")%>%
  
  #add basemaps
  addTiles(group = "OSM (default)") %>%
  addProviderTiles(providers$Stadia.StamenToner, group = "Toner") %>%
  addProviderTiles(providers$Stadia.StamenTonerLite, group = "Toner Lite") %>%
  addProviderTiles(providers$CartoDB.Positron, group = "CartoDB")%>%
  
  # add a legend
  addLegend(pal = pal2, values = ~`Hotel count`, group = c("Airbnb","Hotel"), 
            position ="bottomleft", title = "Accomodation count") %>%
  # specify layers control
  addLayersControl(
    baseGroups = c("OSM (default)", "Toner", "Toner Lite", "CartoDB"),
    overlayGroups = c("Airbnb", "Hotels"),
    options = layersControlOptions(collapsed = FALSE)
  )

# plot the map
map
```

git clone --mirror https://github.com/iantsern-twuk/repository.git CASA0005_GIS-and-Science-clean
